---
title: "Tugas Kuliah IPM"
author: "Adinda Maudy Maulidya"
date: "2025-09-02"
output: html_document
---
```{r}
library(lmtest)
library(orcutt)
library(HoRM)
```

```{r}
Tahun <- 2004:2013
IPM <- c(61.96, 62.95, 65.26, 66.22, 66.78, 67.39, 67.75, 68.40, 68.89, 69.52)
data <- data.frame(Tahun, IPM)

# Lihat datanya
print(data)
```
```{r}
# Membuat model regresi OLS (Ordinary Least Squares)
model_awal <- lm(IPM ~ Tahun, data = data)
summary(model_awal)
```
```{r}
plot(ts(IPM))
points(IPM, col="red")
```
```{r}
# Ambil sisaan dari model
sisaan_awal <- residuals(model_awal)

# Plot sisaan terhadap waktu
plot(data$Tahun, sisaan_awal, type="o", pch=20, col="red",
     main="Plot Sisaan vs Waktu", xlab="Tahun", ylab="Sisaan")
abline(h=0, lty=2) # Garis referensi di y=0
```
```{r}
dwtest(model_awal)
```
```{r}
model_co <- cochrane.orcutt(model_awal)
summary(model_co)

# rho paling optimum
rho <- model_co$rho
cat("Rho optimum:", rho)
```
```{r}
ipm.trans <- data$IPM[-1] - data$IPM[-10]*rho

tahun.trans <- data$Tahun[-1] - data$Tahun[-10]*rho
model_co_manual <- lm(ipm.trans~tahun.trans)

b0_co_manual <- coef(model_co_manual)[1]/(1-rho)
b1_co_manual <- coef(model_co_manual)[2]
cat("Koefisien manual Cochrane-Orcutt:\n")
cat("b0:", b0_co_manual, "\n")
cat("b1:", b1_co_manual, "\n")
```
```{r}
#Penanganan Autokorelasi Hildreth lu
# Hildreth-Lu
hildreth.lu.func<- function(r, model){
  x <- model.matrix(model)[,-1]
  y <- model.response(model.frame(model))
  n <- length(y)
  t <- 2:n
  y <- y[t]-r*y[t-1]
  x <- x[t]-r*x[t-1]
  
  return(lm(y~x))
}

#Pencariab rho yang meminimumkan SSE
r <- c(seq(0.1,0.9, by= 0.1))
tab <- data.frame("rho" = r, "SSE" = sapply(r, function(i){deviance(hildreth.lu.func(i, model_awal))}))
round(tab, 4)
```
```{r}
#Rho optimal di sekitar 0.5
rOpt <- seq(0.4,0.8, by= 0.001)
tabOpt <- data.frame("rho" = rOpt, "SSE" = sapply(rOpt, function(i){deviance(hildreth.lu.func(i, model_awal))}))
head(tabOpt[order(tabOpt$SSE),])
```
```{r}
#Grafik SSE optimum
par(mfrow = c(1,1))
plot(tab$SSE ~ tab$rho , type = "l", xlab = "Rho", ylab = "SSE")
abline(v = tabOpt[tabOpt$SSE==min(tabOpt$SSE),"rho"], lty = 2, col="red",lwd=2)
text(x=0.612	, y=	1.223647	, labels = "rho=0.612", cex = 0.8)
```
```{r}
model_hl <- hildreth.lu(data$IPM, data$Tahun, rho = 0.612)
summary(model_hl)
```
```{r}
#Transformasi Balik
cat("y = ", coef(model_hl)[1]/(1-0.612), "+", coef(model_hl)[2],"x", sep = "")
```
```{r}
#Deteksi autokorelasi
dwtest(model_hl)
```
```{r}
# Menghitung SSE untuk setiap model secara manual
sse_awal <- sum(residuals(model_awal)^2)
sse_co <- sum(residuals(model_co)^2)
sse_hl <- sum(residuals(model_hl)^2)

# Membuat tabel perbandingan
data.frame(
  Metode = c("Model Awal (Sakit)", "Cochrane-Orcutt (Sehat)", "Hildreth-Lu (Sehat)"),
  SSE = c(sse_awal, sse_co, sse_hl),
  DW_Statistic = c(dwtest(model_awal)$statistic, model_co$DW[3], dwtest(model_hl)$statistic)
)
```
